name: Report a bug
description: Something is not working correctly.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report! Your issue will be public, so **do not include any personal information**.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Write a brief sentence about the bug
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
      placeholder: When I do this, that is supposed to happen
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: What actually happened instead? If you have a screenshot or video, attach them.
      placeholder: When I do this, it instead does that
  - type: textarea
    id: repro-steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce the issue?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
  - type: textarea
    id: other-details
    attributes:
      label: Other details
      description: Is there anything else we should know or have?
      placeholder: The bug can only be reproduced this percent of the time
  - type: input
    id: version
    attributes:
      label: InstaWebhooks version
      description: What version are you running? (Use `instawebhooks --version` to see your version)
      placeholder: 0.1.0
  - type: input
    id: python-version
    attributes:
      label: Python version
      description: What version are you running? (Use `python -v` to see your version)
      placeholder: 3.8.0b2+
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: What platforms are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - macOS
        - Linux
        - Other
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/RyanLua/InstaWebhooks?tab=coc-ov-file).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
