blank_issues_enabled: true
contact_links:
  - name: Get GitHub community support
    url: https://github.com/RyanLua/InstaWebhooks/discussions
    about: Get support/help from the GitHub Discussions community.
