blank_issues_enabled: true
contact_links:
  - name: Get community support
    url: https://github.com/RyanLua/InstaWebhooks/discussions
    about: Get help from the [GitHub Discussions](https://github.com/RyanLua/InstaWebhooks/discussions) community.
